// <auto-generated />
using System;
using CGEasy.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGEasy.Core.Migrations
{
    [DbContext(typeof(CGEasyDbContext))]
    [Migration("20251120173205_AddAllRemainingTables")]
    partial class AddAllRemainingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGEasy.Core.Models.Argomento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Argomenti_Nome");

                    b.ToTable("argomenti", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.AssociazioneMastrino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<string>("BilancioDescrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bilancio_descrizione");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<int>("CreatoBy")
                        .HasColumnType("int")
                        .HasColumnName("creato_by");

                    b.Property<string>("CreatoByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("creato_by_name");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descrizione");

                    b.Property<int>("Mese")
                        .HasColumnType("int")
                        .HasColumnName("mese");

                    b.Property<int>("NumeroMappature")
                        .HasColumnType("int")
                        .HasColumnName("numero_mappature");

                    b.Property<string>("TemplatNome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("template_nome");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_AssociazioneMastrino_ClienteId");

                    b.HasIndex("Anno", "Mese")
                        .HasDatabaseName("IX_AssociazioneMastrino_AnnoMese");

                    b.ToTable("associazione_mastrini", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.AssociazioneMastrinoDettaglio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociazioneId")
                        .HasColumnType("int")
                        .HasColumnName("associazione_id");

                    b.Property<string>("CodiceMastrino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codice_mastrino");

                    b.Property<string>("DescrizioneMastrino")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descrizione_mastrino");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<string>("TemplateCodice")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("template_codice");

                    b.Property<string>("TemplateDescrizione")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("template_descrizione");

                    b.Property<string>("TemplateSegno")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("template_segno");

                    b.Property<int?>("TemplateVoceId")
                        .HasColumnType("int")
                        .HasColumnName("template_voce_id");

                    b.HasKey("Id");

                    b.HasIndex("AssociazioneId")
                        .HasDatabaseName("IX_AssociazioneMastrinoDettaglio_AssociazioneId");

                    b.ToTable("associazione_mastrini_dettagli", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Azione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("azione");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione");

                    b.Property<string>("Entita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entita");

                    b.Property<int?>("IdEntita")
                        .HasColumnType("int")
                        .HasColumnName("id_entita");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int")
                        .HasColumnName("id_utente");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.Property<string>("ValoriNuovi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valori_nuovi");

                    b.Property<string>("ValoriPrecedenti")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valori_precedenti");

                    b.HasKey("Id");

                    b.HasIndex("Azione")
                        .HasDatabaseName("IX_AuditLogs_Azione");

                    b.HasIndex("Entita")
                        .HasDatabaseName("IX_AuditLogs_Entita");

                    b.HasIndex("IdUtente")
                        .HasDatabaseName("IX_AuditLogs_IdUtente");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Banca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnticipoFattureMassimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("anticipo_fatture_massimo");

                    b.Property<string>("CodiceIdentificativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codice_identificativo");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataUltimaModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("FidoCCAccordato")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fido_cc_accordato");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("iban");

                    b.Property<decimal>("InteresseAnticipoFatture")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("interesse_anticipo_fatture");

                    b.Property<string>("NomeBanca")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_banca");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("SaldoDelGiorno")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_del_giorno");

                    b.HasKey("Id");

                    b.HasIndex("NomeBanca")
                        .HasDatabaseName("IX_Banche_NomeBanca");

                    b.ToTable("banche", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BancaIncasso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<bool>("AnticipoChiuso_CC")
                        .HasColumnType("bit")
                        .HasColumnName("anticipo_chiuso_cc");

                    b.Property<bool>("AnticipoGestito_CC")
                        .HasColumnType("bit")
                        .HasColumnName("anticipo_gestito_cc");

                    b.Property<int>("BancaId")
                        .HasColumnType("int")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataFatturaCliente")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fattura_cliente");

                    b.Property<DateTime?>("DataIncassoEffettivo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_incasso_effettivo");

                    b.Property<DateTime?>("DataInizioAnticipo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inizio_anticipo");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza");

                    b.Property<DateTime?>("DataScadenzaAnticipo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza_anticipo");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_modifica");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<bool>("Incassato")
                        .HasColumnType("bit")
                        .HasColumnName("incassato");

                    b.Property<int>("Mese")
                        .HasColumnType("int")
                        .HasColumnName("mese");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("NumeroFatturaCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_fattura_cliente");

                    b.Property<decimal>("PercentualeAnticipo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentuale_anticipo");

                    b.HasKey("Id");

                    b.HasIndex("Anno")
                        .HasDatabaseName("IX_BancaIncassi_Anno");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("IX_BancaIncassi_BancaId");

                    b.HasIndex("DataScadenza")
                        .HasDatabaseName("IX_BancaIncassi_DataScadenza");

                    b.HasIndex("Mese")
                        .HasDatabaseName("IX_BancaIncassi_Mese");

                    b.ToTable("banca_incassi", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BancaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int>("BancaId")
                        .HasColumnType("int")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataFatturaFornitore")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fattura_fornitore");

                    b.Property<DateTime?>("DataInizioAnticipo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inizio_anticipo");

                    b.Property<DateTime?>("DataPagamentoEffettivo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_pagamento_effettivo");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza");

                    b.Property<DateTime?>("DataScadenzaAnticipo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza_anticipo");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_modifica");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<int>("Mese")
                        .HasColumnType("int")
                        .HasColumnName("mese");

                    b.Property<string>("NomeFornitore")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_fornitore");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("NumeroFatturaFornitore")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_fattura_fornitore");

                    b.Property<bool>("Pagato")
                        .HasColumnType("bit")
                        .HasColumnName("pagato");

                    b.Property<decimal>("PercentualeAnticipo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentuale_anticipo");

                    b.HasKey("Id");

                    b.HasIndex("Anno")
                        .HasDatabaseName("IX_BancaPagamenti_Anno");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("IX_BancaPagamenti_BancaId");

                    b.HasIndex("DataScadenza")
                        .HasDatabaseName("IX_BancaPagamenti_DataScadenza");

                    b.HasIndex("Mese")
                        .HasDatabaseName("IX_BancaPagamenti_Mese");

                    b.ToTable("banca_pagamenti", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BancaSaldoGiornaliero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BancaId")
                        .HasColumnType("int")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo");

                    b.HasKey("Id");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("IX_BancaSaldoGiornaliero_BancaId");

                    b.HasIndex("Data")
                        .HasDatabaseName("IX_BancaSaldoGiornaliero_Data");

                    b.ToTable("banca_saldo_giornaliero", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BancaUtilizzoAnticipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BancaId")
                        .HasColumnType("int")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataInizioUtilizzo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inizio_utilizzo");

                    b.Property<DateTime?>("DataRimborsoEffettivo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_rimborso_effettivo");

                    b.Property<DateTime>("DataScadenzaUtilizzo")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza_utilizzo");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_modifica");

                    b.Property<decimal>("Fatturato")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fatturato");

                    b.Property<decimal>("ImportoUtilizzo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo_utilizzo");

                    b.Property<decimal>("InteressiMaturati")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("interessi_maturati");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("PercentualeAnticipo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentuale_anticipo");

                    b.Property<bool>("Rimborsato")
                        .HasColumnType("bit")
                        .HasColumnName("rimborsato");

                    b.HasKey("Id");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("IX_BancaUtilizzoAnticipo_BancaId");

                    b.HasIndex("DataInizioUtilizzo")
                        .HasDatabaseName("IX_BancaUtilizzoAnticipo_DataInizio");

                    b.HasIndex("DataScadenzaUtilizzo")
                        .HasDatabaseName("IX_BancaUtilizzoAnticipo_DataScadenza");

                    b.ToTable("banca_utilizzo_anticipo", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BilancioContabile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<string>("CodiceMastrino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codice_mastrino");

                    b.Property<DateTime>("DataImport")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_import");

                    b.Property<string>("DescrizioneBilancio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione_bilancio");

                    b.Property<string>("DescrizioneMastrino")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descrizione_mastrino");

                    b.Property<int>("ImportedBy")
                        .HasColumnType("int")
                        .HasColumnName("imported_by");

                    b.Property<string>("ImportedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("imported_by_name");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<int>("Mese")
                        .HasColumnType("int")
                        .HasColumnName("mese");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("TipoBilancio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_bilancio");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_BilancioContabile_ClienteId");

                    b.HasIndex("Anno", "Mese")
                        .HasDatabaseName("IX_BilancioContabile_AnnoMese");

                    b.ToTable("bilancio_contabile", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.BilancioTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<string>("CodiceMastrino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codice_mastrino");

                    b.Property<DateTime>("DataImport")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_import");

                    b.Property<string>("DescrizioneBilancio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione_bilancio");

                    b.Property<string>("DescrizioneMastrino")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descrizione_mastrino");

                    b.Property<string>("Formula")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("formula");

                    b.Property<string>("Gruppo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gruppo");

                    b.Property<string>("GruppoPadre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("gruppo_padre");

                    b.Property<int>("ImportedBy")
                        .HasColumnType("int")
                        .HasColumnName("imported_by");

                    b.Property<string>("ImportedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("imported_by_name");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<int>("Livello")
                        .HasColumnType("int")
                        .HasColumnName("livello");

                    b.Property<int>("Mese")
                        .HasColumnType("int")
                        .HasColumnName("mese");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("Ordine")
                        .HasColumnType("int")
                        .HasColumnName("ordine");

                    b.Property<string>("Segno")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("segno");

                    b.Property<string>("TipoBilancio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_bilancio");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_BilancioTemplate_ClienteId");

                    b.HasIndex("Anno", "Mese")
                        .HasDatabaseName("IX_BilancioTemplate_AnnoMese");

                    b.ToTable("bilancio_template", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Circolare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int>("ArgomentoId")
                        .HasColumnType("int")
                        .HasColumnName("argomento_id");

                    b.Property<DateTime>("DataImportazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_importazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nome_file");

                    b.Property<string>("PercorsoFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("percorso_file");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("Anno")
                        .HasDatabaseName("IX_Circolari_Anno");

                    b.HasIndex("ArgomentoId")
                        .HasDatabaseName("IX_Circolari_ArgomentoId");

                    b.HasIndex("DataImportazione")
                        .HasDatabaseName("IX_Circolari_DataImportazione");

                    b.ToTable("circolari", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cap");

                    b.Property<string>("CfCliente")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("cf_cliente");

                    b.Property<string>("CfLegaleRappresentante")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("cf_legale_rappresentante");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("citta");

                    b.Property<string>("CodiceAteco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codice_ateco");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataAttivazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_attivazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("IdProfessionista")
                        .HasColumnType("int")
                        .HasColumnName("id_professionista");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("indirizzo");

                    b.Property<string>("LegaleRappresentante")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("legale_rappresentante");

                    b.Property<string>("MailCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("mail_cliente");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("PivaCliente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("piva_cliente");

                    b.Property<string>("Provincia")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("provincia");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_Clienti_Attivo");

                    b.HasIndex("CfCliente")
                        .HasDatabaseName("IX_Clienti_CfCliente");

                    b.HasIndex("IdProfessionista")
                        .HasDatabaseName("IX_Clienti_IdProfessionista");

                    b.HasIndex("NomeCliente")
                        .HasDatabaseName("IX_Clienti_NomeCliente");

                    b.HasIndex("PivaCliente")
                        .HasDatabaseName("IX_Clienti_PivaCliente");

                    b.ToTable("clienti", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.FinanziamentoImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BancaId")
                        .HasColumnType("int")
                        .HasColumnName("banca_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataFattura")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fattura");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_fine");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inizio");

                    b.Property<decimal>("Importo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importo");

                    b.Property<int>("IncassoId")
                        .HasColumnType("int")
                        .HasColumnName("incasso_id");

                    b.Property<string>("NomeFinanziamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_finanziamento");

                    b.Property<string>("NomeFornitore")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_fornitore");

                    b.Property<string>("NumeroFattura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_fattura");

                    b.Property<int>("PagamentoId")
                        .HasColumnType("int")
                        .HasColumnName("pagamento_id");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("BancaId")
                        .HasDatabaseName("IX_FinanziamentoImport_BancaId");

                    b.HasIndex("DataInizio")
                        .HasDatabaseName("IX_FinanziamentoImport_DataInizio");

                    b.ToTable("finanziamento_import", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.IndiceConfigurazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoria");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodiceIndice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("codice_indice");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("descrizione");

                    b.Property<string>("DettagliCalcoloJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dettagli_calcolo_json");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("formula");

                    b.Property<bool>("IsAbilitato")
                        .HasColumnType("bit")
                        .HasColumnName("is_abilitato");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("bit")
                        .HasColumnName("is_standard");

                    b.Property<string>("NomeIndice")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_indice");

                    b.Property<int>("Ordinamento")
                        .HasColumnType("int")
                        .HasColumnName("ordinamento");

                    b.Property<DateTime?>("UltimaModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ultima_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unita_misura");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_IndiceConfigurazione_Categoria");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_IndiceConfigurazione_ClienteId");

                    b.HasIndex("CodiceIndice")
                        .HasDatabaseName("IX_IndiceConfigurazione_CodiceIndice");

                    b.HasIndex("IsAbilitato")
                        .HasDatabaseName("IX_IndiceConfigurazione_IsAbilitato");

                    b.ToTable("indice_configurazione", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.IndicePersonalizzato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodiciDenominatoreJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codici_denominatore");

                    b.Property<string>("CodiciNumeratoreJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codici_numeratore");

                    b.Property<int>("CreatoBy")
                        .HasColumnType("int")
                        .HasColumnName("creato_by");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione");

                    b.Property<decimal>("Moltiplicatore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("moltiplicatore");

                    b.Property<string>("NomeIndice")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_indice");

                    b.Property<string>("Operatore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operatore");

                    b.Property<string>("OperazioneDenominatore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operazione_denominatore");

                    b.Property<string>("OperazioneNumeratore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operazione_numeratore");

                    b.Property<int>("Ordine")
                        .HasColumnType("int")
                        .HasColumnName("ordine");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("unita_misura");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_IndicePersonalizzato_ClienteId");

                    b.ToTable("indici_personalizzati", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.LicenseClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistrazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registrazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PartitaIva")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("partita_iva");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_LicenseClients_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_LicenseClients_IsActive");

                    b.HasIndex("NomeCliente")
                        .HasDatabaseName("IX_LicenseClients_NomeCliente");

                    b.ToTable("license_clients", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.LicenseKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataGenerazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_generazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza");

                    b.Property<string>("FullKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_key");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("generated_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("LicenseClientId")
                        .HasColumnType("int")
                        .HasColumnName("license_client_id");

                    b.Property<string>("LicenseGuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("license_guid");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module_name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_LicenseKeys_IsActive");

                    b.HasIndex("LicenseClientId")
                        .HasDatabaseName("IX_LicenseKeys_ClientId");

                    b.HasIndex("LicenseGuid")
                        .IsUnique()
                        .HasDatabaseName("IX_LicenseKeys_Guid");

                    b.HasIndex("ModuleName")
                        .HasDatabaseName("IX_LicenseKeys_ModuleName");

                    b.ToTable("license_keys", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Professionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataAttivazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_attivazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_Professionisti_Attivo");

                    b.HasIndex("Cognome")
                        .HasDatabaseName("IX_Professionisti_Cognome");

                    b.ToTable("professionisti", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.StatisticaCESalvata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DatiStatisticheJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dati_statistiche_json");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NomeStatistica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_statistica");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_utente");

                    b.Property<string>("PeriodiJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("periodi_json");

                    b.Property<int>("TemplateAnno")
                        .HasColumnType("int")
                        .HasColumnName("template_anno");

                    b.Property<string>("TemplateDescrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("template_descrizione");

                    b.Property<int>("TemplateMese")
                        .HasColumnType("int")
                        .HasColumnName("template_mese");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_StatisticaCESalvata_ClienteId");

                    b.ToTable("statistica_ce_salvata", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.StatisticaSPSalvata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DatiStatisticheJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dati_statistiche_json");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("NomeStatistica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_statistica");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_utente");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PeriodiJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("periodi_json");

                    b.Property<int>("TemplateAnno")
                        .HasColumnType("int")
                        .HasColumnName("template_anno");

                    b.Property<string>("TemplateDescrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("template_descrizione");

                    b.Property<int>("TemplateMese")
                        .HasColumnType("int")
                        .HasColumnName("template_mese");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int")
                        .HasColumnName("utente_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_StatisticaSPSalvata_ClienteId");

                    b.ToTable("statistica_sp_salvata", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.TipoPratica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descrizione");

                    b.Property<int?>("DurataStimataGiorni")
                        .HasColumnType("int")
                        .HasColumnName("durata_stimata_giorni");

                    b.Property<string>("NomePratica")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome_pratica");

                    b.Property<int>("Ordine")
                        .HasColumnType("int")
                        .HasColumnName("ordine");

                    b.Property<int>("PrioritaDefault")
                        .HasColumnType("int")
                        .HasColumnName("priorita_default");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_TipoPratiche_Attivo");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_TipoPratiche_Categoria");

                    b.HasIndex("NomePratica")
                        .HasDatabaseName("IX_TipoPratiche_NomePratica");

                    b.HasIndex("Ordine")
                        .HasDatabaseName("IX_TipoPratiche_Ordine");

                    b.ToTable("tipo_pratiche", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.TodoStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllegatiJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]")
                        .HasColumnName("allegati_json");

                    b.Property<int>("Categoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<int>("CreatoreId")
                        .HasColumnType("int")
                        .HasColumnName("creatore_id");

                    b.Property<string>("CreatoreNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("creatore_nome");

                    b.Property<DateTime?>("DataCompletamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_completamento");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_inizio");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_scadenza");

                    b.Property<DateTime?>("DataUltimaModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_ultima_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descrizione");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<TimeSpan?>("OrarioFine")
                        .HasColumnType("time")
                        .HasColumnName("orario_fine");

                    b.Property<TimeSpan?>("OrarioInizio")
                        .HasColumnType("time")
                        .HasColumnName("orario_inizio");

                    b.Property<int>("Priorita")
                        .HasColumnType("int")
                        .HasColumnName("priorita");

                    b.Property<string>("ProfessionistiAssegnatiIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]")
                        .HasColumnName("professionisti_assegnati_ids_json");

                    b.Property<string>("ProfessionistiAssegnatiNomiJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]")
                        .HasColumnName("professionisti_assegnati_nomi_json");

                    b.Property<int>("Stato")
                        .HasColumnType("int")
                        .HasColumnName("stato");

                    b.Property<int?>("TipoPraticaId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_pratica_id");

                    b.Property<string>("TipoPraticaNome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tipo_pratica_nome");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("titolo");

                    b.HasKey("Id");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_TodoStudio_Categoria");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_TodoStudio_ClienteId");

                    b.HasIndex("CreatoreId")
                        .HasDatabaseName("IX_TodoStudio_CreatoreId");

                    b.HasIndex("DataCreazione")
                        .HasDatabaseName("IX_TodoStudio_DataCreazione");

                    b.HasIndex("DataScadenza")
                        .HasDatabaseName("IX_TodoStudio_DataScadenza");

                    b.HasIndex("Priorita")
                        .HasDatabaseName("IX_TodoStudio_Priorita");

                    b.HasIndex("Stato")
                        .HasDatabaseName("IX_TodoStudio_Stato");

                    b.HasIndex("TipoPraticaId")
                        .HasDatabaseName("IX_TodoStudio_TipoPraticaId");

                    b.ToTable("todo_studio", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.UserPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClientiCreate")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_create");

                    b.Property<bool>("ClientiDelete")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_delete");

                    b.Property<bool>("ClientiRead")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_read");

                    b.Property<bool>("ClientiUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_update");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int")
                        .HasColumnName("id_utente");

                    b.Property<bool>("ModuloBilanci")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_bilanci");

                    b.Property<bool>("ModuloCircolari")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_circolari");

                    b.Property<bool>("ModuloControlloGestione")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_controllo_gestione");

                    b.Property<bool>("ModuloTodo")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_todo");

                    b.Property<bool>("ProfessionistiCreate")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_create");

                    b.Property<bool>("ProfessionistiDelete")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_delete");

                    b.Property<bool>("ProfessionistiRead")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_read");

                    b.Property<bool>("ProfessionistiUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_update");

                    b.Property<bool>("TipoPraticheCreate")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_create");

                    b.Property<bool>("TipoPraticheDelete")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_delete");

                    b.Property<bool>("TipoPraticheRead")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_read");

                    b.Property<bool>("TipoPraticheUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_update");

                    b.Property<bool>("UtentiManage")
                        .HasColumnType("bit")
                        .HasColumnName("utenti_manage");

                    b.HasKey("Id");

                    b.HasIndex("IdUtente")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPermissions_IdUtente");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int")
                        .HasColumnName("ruolo");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_accesso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_Utenti_Attivo");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Utenti_Email");

                    b.HasIndex("Ruolo")
                        .HasDatabaseName("IX_Utenti_Ruolo");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Utenti_Username");

                    b.ToTable("utenti", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
