// <auto-generated />
using System;
using CGEasy.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CGEasy.Core.Migrations
{
    [DbContext(typeof(CGEasyDbContext))]
    [Migration("20251120140550_AddClientiTable")]
    partial class AddClientiTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGEasy.Core.Models.Professionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataAttivazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_attivazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_Professionisti_Attivo");

                    b.HasIndex("Cognome")
                        .HasDatabaseName("IX_Professionisti_Cognome");

                    b.ToTable("professionisti", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.UserPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClientiCreate")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_create");

                    b.Property<bool>("ClientiDelete")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_delete");

                    b.Property<bool>("ClientiRead")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_read");

                    b.Property<bool>("ClientiUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("clienti_update");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IdUtente")
                        .HasColumnType("int")
                        .HasColumnName("id_utente");

                    b.Property<bool>("ModuloBilanci")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_bilanci");

                    b.Property<bool>("ModuloCircolari")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_circolari");

                    b.Property<bool>("ModuloControlloGestione")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_controllo_gestione");

                    b.Property<bool>("ModuloTodo")
                        .HasColumnType("bit")
                        .HasColumnName("modulo_todo");

                    b.Property<bool>("ProfessionistiCreate")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_create");

                    b.Property<bool>("ProfessionistiDelete")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_delete");

                    b.Property<bool>("ProfessionistiRead")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_read");

                    b.Property<bool>("ProfessionistiUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("professionisti_update");

                    b.Property<bool>("TipoPraticheCreate")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_create");

                    b.Property<bool>("TipoPraticheDelete")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_delete");

                    b.Property<bool>("TipoPraticheRead")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_read");

                    b.Property<bool>("TipoPraticheUpdate")
                        .HasColumnType("bit")
                        .HasColumnName("tipopratiche_update");

                    b.Property<bool>("UtentiManage")
                        .HasColumnType("bit")
                        .HasColumnName("utenti_manage");

                    b.HasKey("Id");

                    b.HasIndex("IdUtente")
                        .IsUnique()
                        .HasDatabaseName("IX_UserPermissions_IdUtente");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("CGEasy.Core.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit")
                        .HasColumnName("attivo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cognome");

                    b.Property<DateTime?>("DataCessazione")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_cessazione");

                    b.Property<DateTime>("DataCreazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_creazione")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DataModifica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_modifica")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int")
                        .HasColumnName("ruolo");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_accesso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Attivo")
                        .HasDatabaseName("IX_Utenti_Attivo");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Utenti_Email");

                    b.HasIndex("Ruolo")
                        .HasDatabaseName("IX_Utenti_Ruolo");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Utenti_Username");

                    b.ToTable("utenti", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
